title: My first blog
author: Soham Das
email: dassoham101@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Hello world how is everyone enjoying their vacation and are you excited like me for the new year that is about to come. If yes than let me know how are you spending your days and why are you
  excitd for th new year!!! 
  Also you could tell me what worries you the most in 2020 and also did you like this year(I didn't).

# social links
twitter_username: currently not having!
github_username:  SohamDas101

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
